### ISSUE TITLE
[BUG - MISSION CRITICAL] Website Downtime

### ISSUE THREAD

**Issue by ahmadk953** [ahmadk953/threads-clone#12]
# DEATAILS
The website unexpectedly stopped working after doing some tests and is now completely unfunctional, displaying this error:
``Application error: a client-side exception has occurred (see the browser console for more information).``
Looking at the browser console, this error is displayed:
```
290-56fb51b50a0dceac.js:1  TypeError: Cannot read properties of null (reading 'default')
    at isStaticRequire (413-f8f38b98cb9340e9.js:1:4312)
    at getImgProps (413-f8f38b98cb9340e9.js:1:5557)
    at 413-f8f38b98cb9340e9.js:1:2998
    at Hf (bf6a786c-78f4de11ea8ef20a.js:9:39239)
    at uh (bf6a786c-78f4de11ea8ef20a.js:9:57055)
    at rx (bf6a786c-78f4de11ea8ef20a.js:9:116945)
    at Lk (bf6a786c-78f4de11ea8ef20a.js:9:94304)
    at bf6a786c-78f4de11ea8ef20a.js:9:94126
    at bf (bf6a786c-78f4de11ea8ef20a.js:9:94133)
    at cf (bf6a786c-78f4de11ea8ef20a.js:9:91778)
```
Running this locally in a dev environment displayed the same issue.

# SCREENSHOTS
(the deployed version)
![image](https://github.com/ahmadk953/threads-clone/assets/103906421/41a15671-d0ce-40f7-bd5c-09f72b8b79bd)
(the one running in the dev environment)
![image](https://github.com/ahmadk953/threads-clone/assets/103906421/4abfc51b-e44f-496b-a083-42765f803531)

**Comment by ahmadk953** [comment]
# UPDATE
I have found the issue - When I was testing, I created a community and then updated its details (name and URL slug) and apparently when it saved those changes to the database, it made the "image" field for the community (the profile picture) "null". 
![image](https://github.com/ahmadk953/threads-clone/assets/103906421/7af13a63-8c6b-47b4-9df7-da114d08ccfa)

**Comment by ahmadk953** [comment]
The issue has been resolved by fixing the field in the database.
